### ISSUE TITLE
ModuleNotFoundError : No module named 'holidays.financial' (error about holidays version)

### ISSUE THREAD

**Issue by Jaesung-Jun** [ourownstory/neural_prophet#652] opened 2022-06-05 13:13 UTC
**Prerequisites**

**Describe the bug**

The bug about holidays package in requirements.txt
holidays package is updated to 0.14 in Jun 5.
I think holidays.financial is deprecated in version 0.14

**To Reproduce**

pip install git+https://github.com/ourownstory/neural_prophet.git

**Expected behavior**

Neural Prophet package will successfully load.

**What actually happens**

Error occurred when load Neural Prophet package.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/40080536/172051702-d3f8576e-225f-4cec-aa5c-4e2e963c987a.png)

**Additional context**

To resolve this error, install holidays package in version (>=0.11.1.3, <=0.13)

or

`
pip install "holidays>=0.11.1.3,<0.14"
`

requirments.txt needs to be modified.

**Comment by PavanKumarMS** [comment] 2022-06-28 04:28
HI @Jaesung-Jun , I'm not able to reproduce the issue, I'm successfully able to run the project. Could you please let me know your environment?. Also i created a fresh ubuntu environment to check the issue (Please refer the screenshot attached below).
![Screen Shot 2022-06-28 at 2 24 26 pm](https://user-images.githubusercontent.com/11475120/176092524-83641882-20fa-4bf9-8231-c33eae10c609.png)

**Comment by PavanKumarMS** [comment] 2022-06-28 04:37
Hi @Jaesung-Jun , I'm unable to reproduce the issue on a fresh ubuntu environment. I'm able to import successfully. Could you please let me know your environment?. (I'm attaching my screenshot for reference) 
![Screen Shot 2022-06-28 at 2 35 17 pm](https://user-images.githubusercontent.com/11475120/176093929-3aa813b2-8175-4a9e-8820-f6766fedb0ca.png)

**Comment by Jaesung-Jun** [comment] 2022-07-05 06:51
Thanks to your reply @PavanKumarMS. My environment is Ubuntu 20.04.4 same as you.
Maybe your holiday(python library) version is under 0.15.
As I know, This error only occurs when holiday >= 0.15.

**Comment by noxan** [comment] 2022-08-09 21:09
The issue seems to be reported and fixed upstream, maybe you got a version installed which still suffered from this problem: https://github.com/dr-prodigy/python-holidays/issues/670

For me everything works fine with 0.14.2, guess the issues was with some 0.14.0 or 0.14.1 version. Also I can't find any version >= 0.15  (see [pypi](https://pypi.org/project/holidays/#history)) 🤔

**Comment by ourownstory** [comment] 2022-08-10 19:09
closing based on @noxan comments.
Please reopen if it persists.

**Closed by ourownstory** 2022-08-10 19:09 UTC
