### ISSUE TITLE
Confidence Intervals from forecast

### ISSUE THREAD

**Issue by racoutinho** [ourownstory/neural_prophet#143] opened 2020-12-02 18:52 UTC
Hi all! I'm testing the NeuralProphet and noticed that just like the Prophet, this framework doesn't provide the confidence intervals from the forecast. My question is if this is feasible for this kind of implementation or it`s a feature to be provided soon.

Thanks in advance!!

**Comment by ourownstory** [comment] 2020-12-02 19:46
Hi Roberto, 
Thank you for your question.
We are currently working on adding this capability. 
The overall forecast CI intervals are close to ready to be merged. 
For individual components' CI, it may take a little longer. Do you have use/need for those, too?
Best, Oskar

**Comment by racoutinho** [comment] 2020-12-03 12:45
Hi Oskar, thanks for your reply. For now, the overall forecast CI intervals are enough.
Best regards!

**Comment by ourownstory** [comment] 2020-12-03 22:51
@HansikaPH is working on said feature. She'll link her PR to this issue soon.

**Comment by ourownstory** [comment] 2020-12-05 22:16
Closing as it is a duplicate of #11 
@racoutinho if you track the linked issue, you'll be notified when it's merged.

**Comment by Zephyr69** [comment] 2022-08-11 12:06
Has there been any news on this? I still fail to figure out how to plot CI using neuralprophet :(. 

I have no problem with this using prophet.

**Comment by fctruter** [comment] 2023-02-10 07:46
Upvote on this topic, would be super useful to be able to plot CIs

**Comment by Kevin-Chen0** [comment] 2023-02-26 16:18
We have two methods to plot prediction/confidence intervals:

1. **Quantile Regression** using `quantiles` param in `NeuralProphet` class (see tutorial [here](https://github.com/ourownstory/neural_prophet/blob/main/tutorials/feature-use/uncertainty_quantile_regression.ipynb))
2. **Split Conformal Prediction** using `.conformal_predict()` method in `NeuralProphet` class (see tutorial [here](https://github.com/ourownstory/neural_prophet/blob/main/tutorials/feature-use/uncertainty_conformal_prediction.ipynb))

**Closed by Kevin-Chen0** 2023-02-26 16:18 UTC
Labels: P3, feature request
