### ISSUE TITLE
NeuralProphet fit error and could not show train progress  when run with vscode juypter in branch 0.5.0rc2 and master

### ISSUE THREAD

**Issue by m2kar** [ourownstory/neural_prophet#1069] opened 2022-12-14 17:29 UTC
**Prerequisites**

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone https://github.com/ourownstory/neural_prophet.git
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solveable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Describe the bug**

NeuralProphet fit error and could not show train progress  when run with vscode python extension.
version: 0.5.0rc2, master is error, 0.4.0 is ok.

**To Reproduce**

1. Using VSCode python extension and the inside jupyter notebook feature
2. running notebook: `neural_prophet/tutorials/application-example/energy_solar_pv.ipynb`
3. After running these code lines 
```
m = NeuralProphet(
    yearly_seasonality=3,
    weekly_seasonality=False,
    daily_seasonality=8,
    growth="off",
    learning_rate=0.1,
)
df_train, df_test = m.split_df(sf_pv_df, freq="H", valid_p=0.10)

metrics = m.fit(df_train, freq="H", validation_df=df_test, progress="plot")
```
6. See error
  - attribute error
  
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/16930652/207664758-e9d51a8c-ef62-4e52-aaf8-db9099dc597e.png">

  - progress show abnormal: 

  <img width="1023" alt="image" src="https://user-images.githubusercontent.com/16930652/207664585-aa71c1df-2311-4c6f-8374-df80fc6a659c.png">
  
**Expected behavior**

progress bar show normally and without attribute error.

**Environement (please complete the following information):**

 - Python environment : python 3.7.13 with pytorch
 - NeuralProphet version and install method: 0.5.0rc2, installed from github
 - vscode: 1.73.1 (extension python: v2022.18.2)

**Comment by noxan** [comment] 2022-12-21 21:21
Thanks for the feedback :)

Just a general notice: there is a final `0.5.0` release, better use it instead of the `rc2`.

The attribute error seems to be related to https://github.com/ourownstory/neural_prophet/pull/1064 and should be fixed in the `main` branch, also most likely independent of the progress bar issues. Would be great if you could double check this.

Regarding the progress bar we also added a few fixes, yet I've never seen the exact issue you described. @karl-richter do you have an idea what might be happening here?

**Comment by noxan** [comment] 2022-12-23 02:18
@m2kar I can confirm the progress bar issue - it's already tracked upstream https://github.com/microsoft/vscode-jupyter/issues/8552

You have to downgrade your `ipywidgets<8` for the time being.

**Closed** 2023-02-04 22:57 UTC
Labels: bug
